services:
  - type: web
    plan: free
    name: todo
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn django_project.wsgi"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4